
spring:
  datasource:
    #    url: ${SPRING_DATASOURCE_URL}
    #    username: ${DATABASE_USERNAME}
    #    password: ${DATABASE_PASSWORD}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://dpg-cplg7cocmk4c739o4vkg-a.singapore-postgres.render.com:5432/domdomdb
    username: domdomroot
    password: jETeW282VGdcn1K5Ln2yAz6vkTyZxSQP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    web-application-type: servlet
  mail:
    host: smtp.gmail.com
    port: 857
    username: ducduc28052002@gmail.com
    password: ksadiufqegfjklho
    properties:
      mail:
        smtp:
          starttls:
            enable:true
          auth: true


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days